# https://leetcode.com/problems/find-the-difference/
# Difficulty: Easy

# Problem
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# Soltuion, O(s+t) time and O(1) space
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        counts1 = collections.Counter(s)
        counts2 = collections.Counter(t)
        for key in counts2:
            if counts2[key] > counts1[key]:
                return key